apiVersion: v1
kind: Secret
metadata:
  name: ingestor-secret
type: Opaque
data:
  kaggle-json: eyJ1c2VybmFtZSI6Im1hdGFudHNhY2giLCJrZXkiOiJkNjdjMjVlZGQ4YTRhOTlkMzE4NmFlMGIzNjFjOGI0OCJ9
  twitter-bearer-token: QUFBQUFBQUFBQUFBQUFBQUFBQUFBSk9Uc2dFQUFBQUFxWjNVbkZ2ZExaNEtHWllaVmxoZzY4WG12bEUlM0RhV3VyUll4aTkzSEJkVnd3MW5SSFNneHA0bjl4Q251ZVNDRWhUbFpVeExsM3N0TElYcAo=
